repos:
  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: gofmt
        language: system
        args: [-w]
        files: \.go$
        description: Runs gofmt on all Go files