apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-pod-mutation-webhook
  namespace: otel-pod-mutation-system
  labels:
    app: otel-pod-mutation-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-pod-mutation-webhook
  template:
    metadata:
      labels:
        app: otel-pod-mutation-webhook
    spec:
      serviceAccountName: otel-pod-mutation-webhook
      containers:
      - name: webhook
        image: harbor.rackspace.koski.co/library/otel-pod-mutation:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
          name: webhook-api
        volumeMounts:
        - name: certs
          mountPath: /etc/certs
          readOnly: true
        env:
        - name: TLS_CERT_FILE
          value: /etc/certs/tls.crt
        - name: TLS_KEY_FILE
          value: /etc/certs/tls.key
        - name: WEBHOOK_PORT
          value: "8443"
        # Enable extensive debug logging
        - name: KLOG_V
          value: "4"
        - name: KLOG_LOGTOSTDERR
          value: "true"
        - name: KLOG_ALSOLOGTOSTDERR
          value: "true"
        - name: KLOG_STDERRTHRESHOLD
          value: "INFO"
        livenessProbe:
          httpGet:
            path: /health
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
      volumes:
      - name: certs
        secret:
          secretName: otel-pod-mutation-webhook-certs