apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- certificate.yaml
- rbac.yaml
- deployment.yaml
- service.yaml
- webhook.yaml

images:
- name: harbor.rackspace.koski.co/library/otel-pod-mutation
  newTag: latest