name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: harbor.rackspace.koski.co
  IMAGE_NAME: library/otel-pod-mutation

jobs:
  test:
    runs-on: otel-pod-mutation-set
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Tidy dependencies
      run: go mod tidy

    - name: Verify dependencies
      run: go mod verify

    - name: Download dependencies
      run: go mod download

    - name: Build binary
      run: go build -o webhook .

    - name: Run tests
      run: go test -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Run go fmt check
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "Code is not formatted properly:"
          gofmt -s -l .
          exit 1
        fi

    - name: Check for suspicious constructs
      run: |
        if command -v staticcheck >/dev/null 2>&1; then
          staticcheck ./...
        else
          echo "staticcheck not available, skipping"
        fi

    - name: Check for ineffective assignments
      run: |
        if command -v ineffassign >/dev/null 2>&1; then
          ineffassign ./...
        else
          echo "ineffassign not available, skipping"
        fi

  build-and-push:
    runs-on: otel-pod-mutation-set
    needs: test
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install Buildah
      run: |
        sudo apt-get update
        sudo apt-get install -y buildah

    - name: Build and push image with Buildah
      run: |
        # Configure buildah for privileged container environment
        export BUILDAH_ISOLATION=chroot
        export STORAGE_DRIVER=vfs
        
        buildah login -u "${{ secrets.HARBOR_USERNAME }}" -p "${{ secrets.HARBOR_PASSWORD }}" ${{ env.REGISTRY }}
        
        buildah build \
          --storage-driver vfs \
          --isolation chroot \
          --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
          .
        
        buildah push --storage-driver vfs ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        buildah push --storage-driver vfs ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  security-scan:
    runs-on: otel-pod-mutation-set
    needs: build-and-push
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
